name: My CI

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -  name: first
       uses: actions/checkout@v4

    -  name: second
       uses: actions/setup-python@v5
       with: 
         python-version: "3.12"

    -  name: install dependencies
       run: pip install -r requirements.txt
    -  name: run test
       run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    steps:
    -  name: configure aws 
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: arn:aws:iam::806168575689:role/GitHubActionsECRPushPolicy
         aws-region: us-east-1
    -  name: Login to ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2


    -  name: checkout the code
       uses: actions/checkout@v4

    -  name: build
       run: docker build -t ${{ steps.login-ecr.outputs.registry }}/cicd-practice:v1 .

    -  name: run
       run: docker run --rm ${{ steps.login-ecr.outputs.registry }}/cicd-practice:v1
    
    -  name: image push
       run: docker push ${{ steps.login-ecr.outputs.registry }}/cicd-practice:v1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    -  name: deploy to ec2
       uses: appleboy/ssh-action@v1.2.2
       with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
           aws ecr get-login-password --region us-east-1 |\
           docker login --username AWS --password-stdin 806168575689.dkr.ecr.us-east-1.amazonaws.com
           docker pull 806168575689.dkr.ecr.us-east-1.amazonaws.com/cicd-practice:v1

           docker stop cicd-practice || true
           docker rm cicd-practice || true
           docker run -d\
             --name cicd-practice \
               806168575689.dkr.ecr.us-east-1.amazonaws.com/cicd-practice:v1
