name: My CI

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -  name: first
       uses: actions/checkout@v4

    -  name: second
       uses: actions/setup-python@v5
       with: 
         python-version: "3.12"

    -  name: install dependencies
       run: pip install -r requirements.txt
    -  name: run test
       run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    steps:
    -  name: configure aws 
       uses: aws-actions/configure-aws-credentials@v4
       with:
         role-to-assume: arn:aws:iam::806168575689:role/GitHubActionsECRPushPolicy
         aws-region: us-east-1
    -  name: Login to ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2


    -  name: checkout the code
       uses: actions/checkout@v4

    -  name: build
       run: docker build -t ${{ steps.login-ecr.outputs.registry }}/cicd-practice:v1 .

    -  name: run
       run: docker run --rm ${{ steps.login-ecr.outputs.registry }}/cicd-practice:v1
    
    -  name: image push
       run: docker push ${{ steps.login-ecr.outputs.registry }}/cicd-practice:v1
