name: My CI

on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -  name: first
       uses: actions/checkout@v4

    -  name: second
       uses: actions/setup-python@v5
       with: 
         python-version: "3.12"

    -  name: install dependencies
       run: pip install -r requirements.txt
    -  name: run test
       run: pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    -  name: checkout the code
       uses: actions/checkout@v4

    -  name: build
       run: docker build -t cicd-practice .

    -  name: run
       run: docker run --rm cicd-practice
